image: atlassian/default-image:latest

definitions:
  services:
    docker:
      memory: 3072
  caches:
    gradle: ~/.gradle/caches
    npm: ~/.npm

pipelines:
  default:
    - step:
        name: 编译后端微服务
        script:
          - cd backend
          - ./gradlew build -x test --no-daemon
        caches:
          - gradle
    - step:
        name: 编译前端
        script:
          - cd frontend
          - npm install
          - npm run build
        caches:
          - npm
    - step:
        name: 部署到本地 Docker
        runs-on:
          - self.hosted
          - windows
        script:
          - cd backend
          - docker compose down --remove-orphans
          - docker compose up -d --build

  branches:
    master:
      - step:
          name: 编译后端微服务
          script:
            - cd backend
            - ./gradlew build -x test --no-daemon
          caches:
            - gradle
      - step:
          name: 编译前端
          script:
            - cd frontend
            - npm install
            - npm run build
          caches:
            - npm
      - step:
          name: 部署到本地 Docker
          runs-on:
            - self.hosted
            - windows
          script:
            - cd backend
            - docker compose down --remove-orphans
            - docker compose up -d --build