plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':exam-common')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    runtimeOnly 'com.mysql:mysql-connector-j'
}

bootJar {
    archiveFileName = 'app.jar'
}

jar {
    enabled = false
}
