CREATE TABLE IF NOT EXISTS security_exam_3 (
    id INT PRIMARY KEY AUTO_INCREMENT,
    type VARCHAR(50) NOT NULL COMMENT '题型',
    question LONGTEXT NOT NULL COMMENT '题目内容（支持HTML格式，可包含图片标签）',
    options JSON NOT NULL COMMENT '选项列表',
    answer JSON NOT NULL COMMENT '正确答案',
    analysis LONGTEXT COMMENT '详细分析（支持HTML格式，可包含图片标签）',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_type (type)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='题目表';
