    CREATE TABLE IF NOT EXISTS users (
      id INT AUTO_INCREMENT PRIMARY KEY,
      openid VARCHAR(100) NOT NULL UNIQUE,
      session_key VARCHAR(100) DEFAULT NULL,
      nickname VARCHAR(100) DEFAULT NULL,
      avatar VARCHAR(500) DEFAULT NULL,
      is_vip TINYINT(1) DEFAULT 0,
      vip_expire DATETIME DEFAULT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      last_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;